---
name: deploy-gh

on:
  push:
    branches:
      - master

jobs:
  frontend-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Extract node version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-node-frontend-${{ hashFiles('./front/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-frontend-
      - name: Build application
        run: make build
      - name: Upload applicaton dist
        uses: actions/upload-artifact@v2
        with:
          name: frontend_build
          path: dist

  deploy-to-gh-pages:
    runs-on: self-hosted

    env:
      CURSIV_ACTOR: "cursiv-bot"
    steps:
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: false
          user_name: "${{ env.CURSIV_ACTOR }}"
          user_email: "${{ env.CURSIV_ACTOR }}@users.noreply.github.com"
          commit_message: "chore(ci): deploy landing page"
