---
name: deploy-gh

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      CURSIV_ACTOR: "cursiv-bot"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache gems modules
        id: cache-node
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: build jekyll website
        uses:  lemonarc/jekyll-action@1.0.0

      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # enable_jekyll: true
          keep_files: false
          user_name: "${{ env.CURSIV_ACTOR }}"
          user_email: "${{ env.CURSIV_ACTOR }}@users.noreply.github.com"
          commit_message: "chore(ci): deploy landing page"
